// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkdxumnvptxqnqqlrhzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZHh1bW52cHR4cW5xcWxyaHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMzEwMzgsImV4cCI6MjA3NzcwNzAzOH0.SYabc3B9oL-le44zXmHWChtKwGOmwwfpDWMFKNaHxJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});